openapi: "3.0.0"
info: 
  title: "TD OpenAPI Sprecification"
  version: "3.3.3"
servers: 
  - url: "http://localhost:8000"
    description: Server
paths: 
  /ingredients:
    get:
      tags:
        - Ingredients
      description: Get all ingredients
      responses:
        '200':
          description: Ingredients Lists
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Ingredients'
                example: 
                  - id: 1
                    name: Laitue
                    price: 800
                    ingredientCategory: VEGETABLE 
                  - id: 2
                    name: Tomate
                    price: 600
                    ingredientCategory: VEGETABLE 
                  - id: 3
                    name: Poulet
                    price: 4500
                    ingredientCategory: ANIMAL 
                  - id: 4
                    name: Chocolat 
                    price: 3000
                    ingredientCategory: OTHER
                  - id: 5
                    name: Beurre
                    price: 2500
                    ingredientCategory: DAILY
  /ingredients/{id}:
    get: 
      tags:
        - Ingredients
      description: Find ingredient by Id 
      parameters:
        - name: id
          in : path 
          required: true
          schema: 
            type: integer
          example: 1
      responses:
        '200':
          description: Ingredient by Id
          content: 
            application/json:
              schema:
                items: 
                  $ref: "#/components/schemas/Ingredients"
                example: 
                  id: 1
                  name: Laitue
                  price: 800
                  ingredientCategory: VEGETABLE 
        '404':
          description: Ingredient not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: Ingredient.id={id) is not found
                code: 404
  /ingredients/{id}/stock:     
    get: 
      tags:
        - Ingredients
      description: Found ingredient by stock
      parameters: 
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
        - name: at
          in : query
          description: stock date time
          required: true
          schema: 
            type: string
            format: date-time
            example: 2024-01-06T12:00:00Z
        - name: unit
          in: query 
          description: stock unit
          required: true
          schema: 
            type: string
            enum: 
              - PCS 
              - KG 
              - L
          example: KG
      responses:
        '200':
          description: Ingredient by stock
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Ingredients"
              example:
                  id: 1
                  name: Laitue
                  price: 800
                  ingredientCategory: VEGETABLE 
                  stockMovement:
                    - id: 1
                      quantity: 0.2
                      type: OUT
                      unit: KG
                      creationDatetime: 2024-01-06T12:00:00Z
        '400':
          description: Bad request, time or unit are required
          content: 
            application/json:
              schema:
                $ref: "#components/schemas/Error"
              example: 
                message: Either mandatory query parameter `at` or `unit` is not provided
                code: 400
        '404':
          description: Ingredient not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: Ingredient.id={id) is not found
                code: 404

  /dish:
    get:
      tags:
        - Dish
      description: getAllDishes
      responses: 
        '200':
          description: List of dishes with all ingredients
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dish'
                example: 
                  - id: 1
                    name: Salade Fraîche
                    price: 3500
                    type: STARTER
                    ingredient: 
                      - id: 1
                        name: Laitue
                        price: 800
                        ingredientCategory: VEGETABLE     
                      - id: 2
                        name: Tomate
                        price: 600
                        ingredientCategory: VEGETABLE 
                  - id: 2
                    name: Poulet Grillé 
                    price: 120000
                    type: MAIN
                    ingredient: 
                      - id: 3
                        name: Poulet
                        price: 4500
                        ingredientCategory: ANIMAL
                  - id: 3
                    name: Riz aux légumes
                    price: null
                    type: MAIN
                    ingredient: []
                  - id: 4 
                    name: Gâteau aux chocolat
                    price: 14000
                    type: DESSERT
                    ingredient: 
                      - id: 4
                        name: Chocolat
                        price: 3000
                        ingredientCategory: OTHER
                      - id: 5 
                        name: Beurre 
                        price: 3000 
                        ingredientCategory: DAIRY 
                  - id: 5
                    name: Salade de fruits
                    price: null
                    type: DESSERT
                    ingredientCategory: []
                    
  /dish/{id}:
    put: 
      tags:
        - Dish
      description: Modify the list of ingredient in dish
      parameters:
        - name: id
          in: path
          required: true
          schema: 
            type: integer
          example: 1
      requestBody:
         description: associate or dissociate dish Ingredient
         content: 
          application/json:
            schema: 
              $ref: "#/components/schemas/Ingredients"
            example:
              - id: 1
                name: Laitue
                price: 800
                ingredientCategory: VEGETABLE
              - id: 3
                name: Oignon
                price: 800
                ingredientCategory: VEGETABLE
              
      responses: 
        '200':
          description: Ingredients updated
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Dish"
              example:
                  id: 1
                  name: Salade Fraîche
                  type: STARTER
                  ingredient:            
                    - id: 1
                      name: Laitue
                      price: 800
                      ingredientCategory: VEGETABLE
                    - id: 3
                      name: Oignon
                      price: 800
                      ingredientCategory: VEGETABLE    
        '400':
          description: Ingredient required
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: an ingredient is required for dish {id}
                code: 400
        '404':
          description: Ingredient not found
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: “Dish.id={id} is not found”
                code: 404

components: 
  schemas:
      Ingredients: 
        required:
         - id
         - name
         - price
         - ingredientsCategory
        properties:
          id: 
            type: integer
            format: byte64
          name: 
            type: string
          price: 
            type: number
          ingredientCategory:
            type: string
            enum: 
              - VEGETABLE
              - ANIMAL 
              - MARINE 
              - DAIRY 
              - OTHER
          stockMovement: 
            $ref: "#/components/schemas/StockMovement"
      Dish: 
        required:
          - id
          - name
          - price
          - type
          - ingredients
        properties:
          id:
            type: integer
            format: byte64
          name:
            type: string
          price: 
            type: number
          type:
            type: string 
            enum: 
              - MAIN
              - STARTER
              - DESSERT
          ingredient:
            type: array
            items:
              $ref: "#/components/schemas/Ingredients"
      StockMovement: 
        required: 
          - id
          - quantity
          - type
          - unit
          - creation_datetime
        properties: 
          id: 
            type: integer
            format: byte64
          quantity: 
            type: number
          type:
            type: string
            enum:
              - IN
              - OUT
          unit: 
            type: string
            enum: 
              - KG
              - LG
              - PCS
          creationDatetime:
             type: string
             format: date-time
      Error:
        type: object 
        required: 
        - message
        - code 
        properties:
          message: 
            type: string   
          code:
            type: integer




           
             
          
            


          


        
      


    
                  
                    




